name: Routine submodule updates
on:
  schedule:
    - cron: '53 19 * * TUE'
  push: 
    branches:
      - 'main'
jobs:
  update_submodules:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: List files in the repository (Useful for debugging)
      run: |
        tree ${{ github.workspace }}
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.6 #install the python needed
    - name: Install requirements
      run: |
        pip install -r auditor/requirements.txt        
    - name: Run column name check and export to docs
      run: |
        python test_columns.py 
    - name: Commit the results
      run: |
        git config --local user.name "robot"
        git add .
        git commit -m "auto submodule updates"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
