name: Routine submodule updates
on:
  schedule:
    - cron: '53 19 * * TUE'
  push: 
    branches:
      - 'main'
jobs:
  update_submodules:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: List files in the repository (Useful for debugging)
      run: |
        ls -lra ${{ github.workspace }}
#       - name: Commit the results
#         run: |
#           git config --local user.name "robot"
#           git add .
#           git commit -m "auto submodule updates"
#       - name: Push changes
#         uses: ad-m/github-push-action@master
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           branch: ${{ github.ref }}
